name: Generate Gradle Wrapper

on:
  push:
    branches:
      - main

jobs:
  generate-wrapper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Generate Gradle Wrapper
      run: gradle wrapper --gradle-version 8.11.1

    - name: Commit and Push Wrapper
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add gradle/wrapper/gradle-wrapper.properties gradlew gradlew.bat
        git commit -m "Auto-generate Gradle wrapper" || echo "No changes to commit"
        git push || echo "No changes to push"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
